version: "3.1"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      DATABASE_DEV: "${DB_DATABASE}"
      DATABASE_TEST: "${TEST_DB_DATABASE}"
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-dbs.sh:/docker-entrypoint-initdb.d/init-dbs.sh
    command: ["bash", "-c", "chmod +x /docker-entrypoint-initdb.d/init-dbs.sh && docker-entrypoint.sh postgres"]
  
volumes:
  postgres_data:
